FROM python3.7

COPY crud-FastApi/requirements.txt requirements.txt

RUN pip install -r requirements.txt

EXPOSE 80

COPY ./book_store book_store

CMD ["uvicorn", "book_store.main:app", "--host", "0.0.0.0", "--port", "80"]
